### ISSUE TITLE
[QUESTION] Please update to 1.20

### ISSUE THREAD

**Issue by nhatngo1303** [X-Niter/HungerIsStamina#9]
have error, update to 1.20 pls :((
`[21:53:26] [Server thread/WARN]: [HIS] Task #124 for HungerIsStamina v1.4.0 generated an exception
java.lang.NoSuchMethodError: 'net.Indyuce.mmocore.api.player.PlayerData net.Indyuce.mmocore.manager.data.PlayerDataManager.get(java.util.UUID)'
	at com.xniter.HungerIsStamina.Listeners.PlayerJumping.lambda$new$0(PlayerJumping.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3830-Spigot-0ca4eb6-36b1076]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by X-Niter** [comment]
Please see #8 for progress being done for 1.20 update.
